### ISSUE TITLE
能给出使用的宏包吗

### ISSUE THREAD

**Issue by linger10101** [SwitWu/FunctionalAnalysisXQHsolution#4]
在看泛函分析的解答，顺便学点Latex语法，但是有些命令总是提示错误，比如\neceeary,\diam，能给出对应的宏包吗，万分感谢

**Comment by SwitWu** [comment]
> 在看泛函分析的解答，顺便学点Latex语法，但是有些命令总是提示错误，比如\neceeary,\diam，能给出对应的宏包吗，万分感谢

这些命令的定义都在文件 `mathexercise.cls` 里面，按理说不会报错
